replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

cloudfrontUrl: ""

aws:
  region: ap-southeast-2

dynamodb:
  tableName: rush-webapp-todos

auth0:
  domain: ""
  audience: ""

serviceAccount:
  create: true
  name: backend
  annotations: {}

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
